language: python
cache: pip
sudo: false
git:
    depth: 3
python:
    - "3.5"
    - "3.6"
# command to install dependencies
install:
    #- pip install numpy
    #- pip install scipy
    - pip install -r requirements.txt
    - pip install codecov

script: 
    - python -m unittest urllookup/test_urllookup.py

after_success:
    - codecov

