language: python
cache: pip
sudo: false
git:
    depth: 3
python:
    - 3.5
    - 3.6

install:
    - pip install -r requirements.txt
    - pip install pytest pytest-cov codecov

script: 
    - py.test -v --cov=./

after_success:
    - codecov

